[gspread]
type = "service_account"
project_id = "dil-okulu-sistemi"
private_key_id = "d030a5afc600b24a06d0fa6e5b5f990edbd4e14d"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDEBslcV1yKQVAW
Y9vyLFx5Jt4ViFqed0f99DO0dVqzNnV1l88Ezoeu/gMS4a27d1GAKc+gYO+SfOdX
Lhd8J1yuLVi0vsQntefhrOMu61ZwlcsNyH//Y8NNk45krIDauLQLKABcubc+GPfZ
jrvyCC7BSQVCUQyrp5hKmZr5VmR007MzLl/d2Lxp3opF98L4Z/Rt5cZdFC2AwgBY
e9C6D/67KCYYQ4h4KNH12ABv7/U16xo9SgvlOH62mzMcld93S4uecq0uCRDSBMFg
Q7MoHP2wCpsjNXYOzDWHolgFqOEkcaciQalAZ4fSrlkk2wTc6qNFwOfvrmY4I72U
Fu142XJjAgMBAAECggEAAJayVGzGLyBU+Bw+W/5GhiX4TnZcrx55ClITjU4NX4Oe
SHlKgfkqIjmc9ZPVBT605aBpmMpRXPAmEoasSX8W4PcF5WDTQPYId+5hO2XZeem4
I8jHNEn7UzfsIEfX66zqRcXAlqoBlFvt3r9tWXkbk3rO+lxlGMVlA1ZcLMGH474l
2AZSpU3uWaa7pblm81sD7qvCkNDll4azc7E3oNQpeSwMk9/NhQ1kH1OD1QbTNRvC
whzx9zWdz8A4DrdkKXFXG1OHXYFyNg3zBw/C0JrFHyu/R0vapLDaT6SsGaA2c+hn
UJF8nQ48LLxEjlD2EAlVNeYpAu63/jNOwpbITpoAAQKBgQDht8GuMLn/n6HCO4WK
tZQJQoc3eFyE82n8Q+W9kOze4XOrRijbegajDnQ4+CoZWFt4DXCT/8AdAnEHkwm+
la+EtITggkus2T+WJYEdVTOxAU2AgXVNfbISzUS04ipOo6reZURDJCNWGV1hl6Z6
jGZ1PyR9tgocqie/L67hLHeyYwKBgQDeU0mF7zuniK+2ykEys0cTG/sTsO/LSZdd
N95WWk0xnKLdD+1iK1u2t6hlIT7uSFdhQIhMfD8qMH3on6UmtDx9XCOnBeN/HY0w
MbhmR+x3ZrVQFjcKs9jW/wekGLYPT6NnRqM6nRdiR61cuznojpqZiiLATNTm560d
r4UVpuNAAQKBgA/Jsppkfh4LJF1ZnHWfTcN4C80tdgs2m2sxtJgV0vuj+Vs5hRIU
7vHoyOhTM16id4NmLUGs2dstmIpXFo9mGOjHV6P8eR6V84SlCurqUrtGxA0BARty
d0opYWzlhOALQqBbpPKtTGtxSr7QxKw9tcztpbfFS9/FZxJQW4MUgSrRAoGBAL1w
lI6GeftYUflcP8/WyTI0Pm3Z74n16/8nUtGb4njqsi/RmYFz1pNLzTZW7MuXYrVg
ioM5v4zQgwjLt6rSG1TqRQrVzrKK2Lp/M1Qb5xcaslZKh54b/yG7b6RY1hEX1/Fx
VDbmkn1Q/ByvADn0ATHhbZkUHrmeIXnRDIKVkMABAoGBANJ+uBmLjVwj6potc4QM
BR6ooSlIurhzEso/ot0fVTAEtKKTVHsnxz+7A7dOcnjRjgyaK4bT/ruTprvfnJ6f
LvY+4+sdu/zMQ39KnnNCVPZCNVa6dlX7UuyRMmGUZkjRkAUXkzAD9yxVWUyu6wsO
en92USHJlns9Vaq6xuLcojIp
-----END PRIVATE KEY-----"""
client_email = "streamlit-danisman@dil-okulu-sistemi.iam.gserviceaccount.com"
client_id = "101001757013925009355"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-danisman@dil-okulu-sistemi.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

