[gspread]
type = "service_account"
project_id = "dil-okulu-sistemi"
private_key_id = "d030a5afc600b24a06d0fa6e5b5f990edbd4e14d"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDEBslcV1yKQVAW
Y9vyLFx5Jt4ViFqed0f99DO0dVqzNnV1l88Ezoeu/gMS4a27d1GAKc+gYO+SfOdX
... (tamam覺 buraya, sat覺r sat覺r, kopyalanmal覺) ...
-----END PRIVATE KEY-----"""
client_email = "streamlit-danisman@dil-okulu-sistemi.iam.gserviceaccount.com"
client_id = "101001757013925009355"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-danisman@dil-okulu-sistemi.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
